package com.roufsyed.onekey.core.domain.usecase

import com.roufsyed.onekey.core.domain.model.AppResult
import com.roufsyed.onekey.core.domain.model.Credential
import com.roufsyed.onekey.core.domain.model.CustomField
import com.roufsyed.onekey.core.domain.model.OtpParams
import com.roufsyed.onekey.core.domain.repository.CredentialRepository
import javax.inject.Inject

class SeedDataUseCase @Inject constructor(
    private val credentialRepository: CredentialRepository,
) {
    suspend operator fun invoke(): AppResult<Int> {
        val now = System.currentTimeMillis()
        var count = 0
        for (credential in sampleCredentials(now)) {
            val result = credentialRepository.saveCredential(credential)
            if (result is AppResult.Success) count++
        }
        return AppResult.Success(count)
    }

    /**
     * Seeds standalone Login credentials each carrying a working RFC6238 TOTP secret,
     * so the 2FA tab populates immediately without scanning a QR code by hand.
     * Titles are suffixed `(2FA Demo)` so they don't collide with [sampleCredentials].
     */
    suspend fun seedTwoFa(): AppResult<Int> {
        val now = System.currentTimeMillis()
        var count = 0
        for (credential in sampleTwoFaCredentials(now)) {
            val result = credentialRepository.saveCredential(credential)
            if (result is AppResult.Success) count++
        }
        return AppResult.Success(count)
    }

    private fun sampleTwoFaCredentials(now: Long): List<Credential> = listOf(
        twoFa(now, "Google (2FA Demo)", "demo.user@gmail.com", "https://accounts.google.com",
            "JBSWY3DPEHPK3PXP", offsetDays = 0),
        twoFa(now, "GitHub (2FA Demo)", "demo-user", "https://github.com",
            "GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ", offsetDays = 1),
        twoFa(now, "AWS Console (2FA Demo)", "demo-aws@example.com", "https://console.aws.amazon.com",
            "MFRGGZDFMZTWQ2LKNNWG23TPN5XGS3DM", offsetDays = 2),
        twoFa(now, "Coinbase (2FA Demo)", "demo.user@gmail.com", "https://coinbase.com",
            "ONSWG4TFOQQGS4ZAONSWG4TFOQQGS4ZA", offsetDays = 3),
        twoFa(now, "Discord (2FA Demo)", "demo_user#1234", "https://discord.com",
            "OBQXG43XN5ZGI4DPNZQXG2LJNZUW4ZZA", offsetDays = 4),
        twoFa(now, "Steam (2FA Demo)", "demo_user_gaming", "https://steamcommunity.com",
            "NRSXOIDBEBSXEYLDNF2GCZ3FORZGS3TH", offsetDays = 5),
        twoFa(now, "Twitter / X (2FA Demo)", "demo_user_x", "https://x.com",
            "MZXW6YTBOI======", offsetDays = 6),
        twoFa(now, "Reddit (2FA Demo)", "demo_user_reddit", "https://reddit.com",
            "KRSXG5BAONUW45BAONUW45BAONUW45BA", offsetDays = 7),
    )

    private fun twoFa(
        now: Long,
        title: String,
        username: String,
        url: String,
        secretBase32: String,
        offsetDays: Int,
    ): Credential = Credential(
        id = "",
        title = title,
        username = username,
        password = "DemoP@ssw0rd!2024",
        url = url,
        notes = "Seeded for 2FA testing - code rotates every 30 seconds.",
        otpParams = OtpParams.defaultTotp(secretBase32),
        tags = listOf("Login"),
        customFields = emptyList(),
        isFavorite = false,
        createdAt = now - offsetDays * 86_400_000L,
        updatedAt = now - offsetDays * 86_400_000L,
    )

    private fun sampleCredentials(now: Long): List<Credential> = listOf(
        Credential(
            id = "",
            title = "Google Account",
            username = "john.doe@gmail.com",
            password = "Str0ng!Passw0rd#2024",
            url = "https://accounts.google.com",
            notes = "Primary Google account used for Gmail and Drive.",
            otpParams = null,
            tags = listOf("Login"),
            customFields = emptyList(),
            isFavorite = true,
            createdAt = now,
            updatedAt = now,
        ),
        Credential(
            id = "",
            title = "GitHub",
            username = "johndoe",
            password = "ghp_ExampleTokenValue123",
            url = "https://github.com",
            notes = "Work GitHub account. 2FA enabled.",
            otpParams = null,
            tags = listOf("Login"),
            customFields = listOf(
                CustomField(key = "Access Token", value = "ghp_ExampleTokenValue123456", isSensitive = true),
            ),
            isFavorite = false,
            createdAt = now,
            updatedAt = now,
        ),
        Credential(
            id = "",
            title = "Home WiFi",
            username = "",
            password = "MyWiFiPassword@Home2024",
            url = "",
            notes = "SSID: MyHomeNetwork_5G. Router admin at 192.168.1.1.",
            otpParams = null,
            tags = listOf("Secure Note"),
            customFields = listOf(
                CustomField(key = "SSID", value = "MyHomeNetwork_5G", isSensitive = false),
                CustomField(key = "Router IP", value = "192.168.1.1", isSensitive = false),
            ),
            isFavorite = false,
            createdAt = now,
            updatedAt = now,
        ),
        Credential(
            id = "",
            title = "Visa Platinum",
            username = "John Doe",
            password = "4532 1234 5678 9012",
            url = "",
            notes = "Expires 12/2027. Billing zip: 10001.",
            otpParams = null,
            tags = listOf("Credit Card"),
            customFields = listOf(
                CustomField(key = "CVV", value = "123", isSensitive = true),
                CustomField(key = "Expiry", value = "12/2027", isSensitive = false),
                CustomField(key = "PIN", value = "1234", isSensitive = true),
            ),
            isFavorite = false,
            createdAt = now,
            updatedAt = now,
        ),
        Credential(
            id = "",
            title = "Netflix",
            username = "john.doe@gmail.com",
            password = "Netf1ix\$ecure!Pass",
            url = "https://netflix.com",
            notes = "Premium plan, shared with family.",
            otpParams = null,
            tags = listOf("Password"),
            customFields = emptyList(),
            isFavorite = false,
            createdAt = now,
            updatedAt = now,
        ),
        Credential(
            id = "",
            title = "Chase Checking",
            username = "john.doe",
            password = "BankingP@ss2024!",
            url = "https://chase.com",
            notes = "Primary checking account.",
            otpParams = null,
            tags = listOf("Bank Account"),
            customFields = listOf(
                CustomField(key = "Account Number", value = "000123456789", isSensitive = true),
                CustomField(key = "Routing Number", value = "021000021", isSensitive = true),
            ),
            isFavorite = true,
            createdAt = now,
            updatedAt = now,
        ),
        Credential(
            id = "",
            title = "Production PostgreSQL",
            username = "prod_admin",
            password = "Pg\$ecureP@ssw0rd!",
            url = "postgres://db.example.com:5432/prod_db",
            notes = "Production DB. Connect via VPN only.",
            otpParams = null,
            tags = listOf("Database"),
            customFields = listOf(
                CustomField(key = "Database", value = "prod_db", isSensitive = false),
                CustomField(key = "Port", value = "5432", isSensitive = false),
            ),
            isFavorite = false,
            createdAt = now,
            updatedAt = now,
        ),
        Credential(
            id = "",
            title = "Work Email",
            username = "john.doe@company.com",
            password = "W0rkEmail!Secure#",
            url = "https://mail.company.com",
            notes = "Corporate email. IMAP port 993, SMTP port 587.",
            otpParams = null,
            tags = listOf("Email Account"),
            customFields = listOf(
                CustomField(key = "IMAP", value = "mail.company.com:993", isSensitive = false),
                CustomField(key = "SMTP", value = "smtp.company.com:587", isSensitive = false),
            ),
            isFavorite = false,
            createdAt = now,
            updatedAt = now,
        ),
        Credential(
            id = "",
            title = "Production VPS",
            username = "root",
            password = "Serv3r\$ecureP@ss!",
            url = "ssh://198.51.100.42:22",
            notes = "Ubuntu 22.04 LTS. 4 GB RAM. DigitalOcean.",
            otpParams = null,
            tags = listOf("Server"),
            customFields = listOf(
                CustomField(key = "IP Address", value = "198.51.100.42", isSensitive = false),
                CustomField(key = "SSH Key", value = "~/.ssh/id_rsa_prod", isSensitive = false),
            ),
            isFavorite = false,
            createdAt = now,
            updatedAt = now,
        ),
        Credential(
            id = "",
            title = "Twitter / X",
            username = "johndoe_x",
            password = "Tw1tt3r\$ecure#2024",
            url = "https://x.com",
            notes = "Personal account. 2FA via authenticator app.",
            otpParams = null,
            tags = listOf("Login"),
            customFields = emptyList(),
            isFavorite = false,
            createdAt = now - 86_400_000L * 3,
            updatedAt = now - 86_400_000L * 3,
        ),
        Credential(
            id = "",
            title = "LinkedIn",
            username = "john.doe@gmail.com",
            password = "L1nked!nP@ss#Pro",
            url = "https://linkedin.com",
            notes = "Professional profile. Premium subscription.",
            otpParams = null,
            tags = listOf("Login"),
            customFields = emptyList(),
            isFavorite = false,
            createdAt = now - 86_400_000L * 7,
            updatedAt = now - 86_400_000L * 7,
        ),
        Credential(
            id = "",
            title = "Instagram",
            username = "johndoe.photo",
            password = "Inst@gr@m!Secure24",
            url = "https://instagram.com",
            notes = "Photography account.",
            otpParams = null,
            tags = listOf("Login"),
            customFields = emptyList(),
            isFavorite = false,
            createdAt = now - 86_400_000L * 10,
            updatedAt = now - 86_400_000L * 10,
        ),
        Credential(
            id = "",
            title = "Facebook",
            username = "john.doe.personal",
            password = "F@ceb00k\$tr0ng!Pass",
            url = "https://facebook.com",
            notes = "Personal account. Rarely used.",
            otpParams = null,
            tags = listOf("Login"),
            customFields = emptyList(),
            isFavorite = false,
            createdAt = now - 86_400_000L * 14,
            updatedAt = now - 86_400_000L * 14,
        ),
        Credential(
            id = "",
            title = "Amazon",
            username = "john.doe@gmail.com",
            password = "Am@z0n\$hop!Secure#",
            url = "https://amazon.com",
            notes = "Prime membership. Default card ending 9012.",
            otpParams = null,
            tags = listOf("Login"),
            customFields = emptyList(),
            isFavorite = true,
            createdAt = now - 86_400_000L * 2,
            updatedAt = now - 86_400_000L * 2,
        ),
        Credential(
            id = "",
            title = "Slack - Acme Corp",
            username = "john.doe@company.com",
            password = "Sl@ckW0rk!P@ss#24",
            url = "https://acmecorp.slack.com",
            notes = "Work Slack workspace. SSO via Google.",
            otpParams = null,
            tags = listOf("Login"),
            customFields = emptyList(),
            isFavorite = false,
            createdAt = now - 86_400_000L * 5,
            updatedAt = now - 86_400_000L * 5,
        ),
        Credential(
            id = "",
            title = "Notion",
            username = "john.doe@gmail.com",
            password = "N0t10n\$ecure!Plan#",
            url = "https://notion.so",
            notes = "Personal + team workspace. Plus plan.",
            otpParams = null,
            tags = listOf("Login"),
            customFields = emptyList(),
            isFavorite = false,
            createdAt = now - 86_400_000L * 6,
            updatedAt = now - 86_400_000L * 6,
        ),
        Credential(
            id = "",
            title = "Spotify",
            username = "john.doe@gmail.com",
            password = "Sp0t1fy!Pr3m1um#24",
            url = "https://spotify.com",
            notes = "Premium individual plan.",
            otpParams = null,
            tags = listOf("Password"),
            customFields = emptyList(),
            isFavorite = true,
            createdAt = now - 86_400_000L * 4,
            updatedAt = now - 86_400_000L * 4,
        ),
        Credential(
            id = "",
            title = "Disney+",
            username = "john.doe@gmail.com",
            password = "D1sney\$tream!P@ss",
            url = "https://disneyplus.com",
            notes = "Standard with ads plan. Family shared.",
            otpParams = null,
            tags = listOf("Password"),
            customFields = emptyList(),
            isFavorite = false,
            createdAt = now - 86_400_000L * 8,
            updatedAt = now - 86_400_000L * 8,
        ),
        Credential(
            id = "",
            title = "PayPal",
            username = "john.doe@gmail.com",
            password = "P@yP@l\$ecure!2024",
            url = "https://paypal.com",
            notes = "Linked to Chase checking. Business + personal.",
            otpParams = null,
            tags = listOf("Bank Account"),
            customFields = listOf(
                CustomField(key = "Business Email", value = "business@johndoe.com", isSensitive = false),
            ),
            isFavorite = true,
            createdAt = now - 86_400_000L * 1,
            updatedAt = now - 86_400_000L * 1,
        ),
        Credential(
            id = "",
            title = "Coinbase",
            username = "john.doe@gmail.com",
            password = "C01nb@se!\$ecure#24",
            url = "https://coinbase.com",
            notes = "Crypto exchange. 2FA mandatory. Keep recovery phrase offline.",
            otpParams = null,
            tags = listOf("Bank Account"),
            customFields = listOf(
                CustomField(key = "Recovery Phrase", value = "stored in safe", isSensitive = true),
            ),
            isFavorite = false,
            createdAt = now - 86_400_000L * 20,
            updatedAt = now - 86_400_000L * 20,
        ),
        Credential(
            id = "",
            title = "AWS Console",
            username = "john.doe+aws@gmail.com",
            password = "AW\$C0ns0le!Secure#",
            url = "https://console.aws.amazon.com",
            notes = "Root account. MFA enabled. Billing alerts set at $50.",
            otpParams = null,
            tags = listOf("Server"),
            customFields = listOf(
                CustomField(key = "Account ID", value = "123456789012", isSensitive = false),
                CustomField(key = "Region", value = "us-east-1", isSensitive = false),
            ),
            isFavorite = true,
            createdAt = now - 86_400_000L * 30,
            updatedAt = now - 86_400_000L * 12,
        ),
        Credential(
            id = "",
            title = "Azure Portal",
            username = "john.doe@company.com",
            password = "Azur3\$ecure!P@ss24",
            url = "https://portal.azure.com",
            notes = "Work Azure subscription. Pay-as-you-go.",
            otpParams = null,
            tags = listOf("Server"),
            customFields = listOf(
                CustomField(key = "Subscription ID", value = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", isSensitive = true),
            ),
            isFavorite = false,
            createdAt = now - 86_400_000L * 25,
            updatedAt = now - 86_400_000L * 25,
        ),
        Credential(
            id = "",
            title = "Vercel",
            username = "johndoe",
            password = "V3rc3l\$ecure!Deploy",
            url = "https://vercel.com",
            notes = "Hobby plan. Linked to GitHub.",
            otpParams = null,
            tags = listOf("Server"),
            customFields = listOf(
                CustomField(key = "API Token", value = "vercel_xxxxxxxxxxxxxxxxxxxx", isSensitive = true),
            ),
            isFavorite = false,
            createdAt = now - 86_400_000L * 9,
            updatedAt = now - 86_400_000L * 9,
        ),
        Credential(
            id = "",
            title = "Docker Hub",
            username = "johndoe",
            password = "D0ck3r\$ecure!Hub24",
            url = "https://hub.docker.com",
            notes = "Free tier. Personal image repositories.",
            otpParams = null,
            tags = listOf("Login"),
            customFields = listOf(
                CustomField(key = "Access Token", value = "dckr_pat_xxxxxxxxxxxx", isSensitive = true),
            ),
            isFavorite = false,
            createdAt = now - 86_400_000L * 11,
            updatedAt = now - 86_400_000L * 11,
        ),
        Credential(
            id = "",
            title = "GitLab",
            username = "john_doe_dev",
            password = "G1tL@b\$ecure!Pass#",
            url = "https://gitlab.com",
            notes = "Self-managed CI/CD pipelines. Work projects.",
            otpParams = null,
            tags = listOf("Login"),
            customFields = listOf(
                CustomField(key = "Personal Token", value = "glpat-xxxxxxxxxxxxxxxxxxxx", isSensitive = true),
            ),
            isFavorite = false,
            createdAt = now - 86_400_000L * 15,
            updatedAt = now - 86_400_000L * 15,
        ),
        Credential(
            id = "",
            title = "Zoom",
            username = "john.doe@company.com",
            password = "Z00m\$ecure!Meet#24",
            url = "https://zoom.us",
            notes = "Work account. Pro plan via company SSO.",
            otpParams = null,
            tags = listOf("Login"),
            customFields = listOf(
                CustomField(key = "Personal Meeting ID", value = "123-456-7890", isSensitive = false),
            ),
            isFavorite = false,
            createdAt = now - 86_400_000L * 13,
            updatedAt = now - 86_400_000L * 13,
        ),
        Credential(
            id = "",
            title = "Figma",
            username = "john.doe@company.com",
            password = "F1gm@\$ecure!Des1gn",
            url = "https://figma.com",
            notes = "Professional plan. Design system repo.",
            otpParams = null,
            tags = listOf("Login"),
            customFields = emptyList(),
            isFavorite = false,
            createdAt = now - 86_400_000L * 16,
            updatedAt = now - 86_400_000L * 16,
        ),
        Credential(
            id = "",
            title = "Jira",
            username = "john.doe@company.com",
            password = "J1r@\$ecure!T1cket#",
            url = "https://acmecorp.atlassian.net",
            notes = "Scrum board for Backend team. Project key: BACK.",
            otpParams = null,
            tags = listOf("Login"),
            customFields = listOf(
                CustomField(key = "API Token", value = "ATATTxxxxxxxxxxxxxxxxxx", isSensitive = true),
            ),
            isFavorite = false,
            createdAt = now - 86_400_000L * 18,
            updatedAt = now - 86_400_000L * 18,
        ),
        Credential(
            id = "",
            title = "Dropbox",
            username = "john.doe@gmail.com",
            password = "Dr0pb0x\$ecure!Plus",
            url = "https://dropbox.com",
            notes = "Plus plan. 2 TB storage. Backup vault.",
            otpParams = null,
            tags = listOf("Login"),
            customFields = emptyList(),
            isFavorite = false,
            createdAt = now - 86_400_000L * 22,
            updatedAt = now - 86_400_000L * 22,
        ),
        Credential(
            id = "",
            title = "iCloud",
            username = "john.doe@icloud.com",
            password = "1Cl0ud!\$ecureApple#",
            url = "https://icloud.com",
            notes = "50 GB storage plan. Linked to iPhone and MacBook.",
            otpParams = null,
            tags = listOf("Login"),
            customFields = emptyList(),
            isFavorite = true,
            createdAt = now - 86_400_000L * 28,
            updatedAt = now - 86_400_000L * 28,
        ),
        Credential(
            id = "",
            title = "ProtonMail",
            username = "johndoe.secure",
            password = "Pr0t0n\$ecure!M@il#",
            url = "https://mail.proton.me",
            notes = "Privacy-first email. Used for sensitive sign-ups.",
            otpParams = null,
            tags = listOf("Email Account"),
            customFields = emptyList(),
            isFavorite = false,
            createdAt = now - 86_400_000L * 35,
            updatedAt = now - 86_400_000L * 35,
        ),
        Credential(
            id = "",
            title = "Outlook Personal",
            username = "johndoe1990@outlook.com",
            password = "0utl00k\$ecure!Pass",
            url = "https://outlook.live.com",
            notes = "Old Microsoft account. Used for Xbox and legacy services.",
            otpParams = null,
            tags = listOf("Email Account"),
            customFields = emptyList(),
            isFavorite = false,
            createdAt = now - 86_400_000L * 40,
            updatedAt = now - 86_400_000L * 40,
        ),
        Credential(
            id = "",
            title = "Wells Fargo Savings",
            username = "johndoe1990",
            password = "W3ll\$F@rgo!\$@vings#",
            url = "https://wellsfargo.com",
            notes = "High-yield savings account.",
            otpParams = null,
            tags = listOf("Bank Account"),
            customFields = listOf(
                CustomField(key = "Account Number", value = "9876543210", isSensitive = true),
                CustomField(key = "Routing Number", value = "121042882", isSensitive = true),
            ),
            isFavorite = false,
            createdAt = now - 86_400_000L * 45,
            updatedAt = now - 86_400_000L * 45,
        ),
        Credential(
            id = "",
            title = "Mastercard Gold",
            username = "John Doe",
            password = "5412 3456 7890 1234",
            url = "",
            notes = "Expires 08/2026. Travel rewards card.",
            otpParams = null,
            tags = listOf("Credit Card"),
            customFields = listOf(
                CustomField(key = "CVV", value = "456", isSensitive = true),
                CustomField(key = "Expiry", value = "08/2026", isSensitive = false),
                CustomField(key = "PIN", value = "5678", isSensitive = true),
            ),
            isFavorite = false,
            createdAt = now - 86_400_000L * 50,
            updatedAt = now - 86_400_000L * 50,
        ),
        Credential(
            id = "",
            title = "Robinhood",
            username = "john.doe@gmail.com",
            password = "R0b1nh00d!\$t0ck#24",
            url = "https://robinhood.com",
            notes = "Brokerage account. Gold subscription.",
            otpParams = null,
            tags = listOf("Bank Account"),
            customFields = listOf(
                CustomField(key = "Account Number", value = "RBH-123456789", isSensitive = true),
            ),
            isFavorite = false,
            createdAt = now - 86_400_000L * 55,
            updatedAt = now - 86_400_000L * 55,
        ),
        Credential(
            id = "",
            title = "Steam",
            username = "johndoe_gaming",
            password = "St3@m\$ecure!G@m3#",
            url = "https://store.steampowered.com",
            notes = "PC gaming library. Family sharing enabled.",
            otpParams = null,
            tags = listOf("Login"),
            customFields = emptyList(),
            isFavorite = true,
            createdAt = now - 86_400_000L * 60,
            updatedAt = now - 86_400_000L * 60,
        ),
        Credential(
            id = "",
            title = "PlayStation Network",
            username = "JohnDoe_PS5",
            password = "P\$N\$ecure!G@m3r#24",
            url = "https://playstation.com",
            notes = "PS Plus Extra subscription. Primary PS5.",
            otpParams = null,
            tags = listOf("Login"),
            customFields = emptyList(),
            isFavorite = false,
            createdAt = now - 86_400_000L * 65,
            updatedAt = now - 86_400_000L * 65,
        ),
        Credential(
            id = "",
            title = "Epic Games",
            username = "johndoe@gmail.com",
            password = "3p1cG@mes!\$ecure#24",
            url = "https://epicgames.com",
            notes = "Free weekly games account.",
            otpParams = null,
            tags = listOf("Login"),
            customFields = emptyList(),
            isFavorite = false,
            createdAt = now - 86_400_000L * 70,
            updatedAt = now - 86_400_000L * 70,
        ),
        Credential(
            id = "",
            title = "NordVPN",
            username = "john.doe@gmail.com",
            password = "N0rdVPN!\$ecure#Pass",
            url = "https://nordvpn.com",
            notes = "2-year plan. 6 devices. Preferred server: US #4562.",
            otpParams = null,
            tags = listOf("Secure Note"),
            customFields = listOf(
                CustomField(key = "Service Key", value = "xxxxxxxxxxxxxxxxxxxxxxxx", isSensitive = true),
            ),
            isFavorite = false,
            createdAt = now - 86_400_000L * 80,
            updatedAt = now - 86_400_000L * 80,
        ),
        Credential(
            id = "",
            title = "Airbnb",
            username = "john.doe@gmail.com",
            password = "@1rbnb\$ecure!H0st#",
            url = "https://airbnb.com",
            notes = "Guest account. Superhost status.",
            otpParams = null,
            tags = listOf("Login"),
            customFields = emptyList(),
            isFavorite = false,
            createdAt = now - 86_400_000L * 90,
            updatedAt = now - 86_400_000L * 90,
        ),
        Credential(
            id = "",
            title = "Booking.com",
            username = "john.doe@gmail.com",
            password = "B00k1ng\$ecure!Tr@v",
            url = "https://booking.com",
            notes = "Genius Level 2 loyalty status.",
            otpParams = null,
            tags = listOf("Login"),
            customFields = emptyList(),
            isFavorite = false,
            createdAt = now - 86_400_000L * 95,
            updatedAt = now - 86_400_000L * 95,
        ),
        Credential(
            id = "",
            title = "United Airlines MileagePlus",
            username = "johndoe1990",
            password = "Un1ted!\$ecure#M1les",
            url = "https://united.com",
            notes = "MileagePlus number: MP123456789. Gold status.",
            otpParams = null,
            tags = listOf("Secure Note"),
            customFields = listOf(
                CustomField(key = "MileagePlus #", value = "MP123456789", isSensitive = false),
                CustomField(key = "PIN", value = "4321", isSensitive = true),
            ),
            isFavorite = false,
            createdAt = now - 86_400_000L * 100,
            updatedAt = now - 86_400_000L * 100,
        ),
        Credential(
            id = "",
            title = "Apple ID",
            username = "john.doe@icloud.com",
            password = "@ppleID\$ecure!2024",
            url = "https://appleid.apple.com",
            notes = "Primary Apple ID. Linked to all Apple devices.",
            otpParams = null,
            tags = listOf("Login"),
            customFields = emptyList(),
            isFavorite = true,
            createdAt = now - 86_400_000L * 110,
            updatedAt = now - 86_400_000L * 20,
        ),
        Credential(
            id = "",
            title = "Microsoft 365",
            username = "john.doe@company.com",
            password = "M\$365\$ecure!W0rk#",
            url = "https://office.com",
            notes = "Work M365 subscription. Teams, Word, Excel, Outlook.",
            otpParams = null,
            tags = listOf("Login"),
            customFields = emptyList(),
            isFavorite = false,
            createdAt = now - 86_400_000L * 120,
            updatedAt = now - 86_400_000L * 30,
        ),
        Credential(
            id = "",
            title = "Staging PostgreSQL",
            username = "staging_admin",
            password = "Stg\$ecureP@ssw0rd!",
            url = "postgres://staging-db.example.com:5432/staging_db",
            notes = "Staging environment DB. Safe to run migrations here first.",
            otpParams = null,
            tags = listOf("Database"),
            customFields = listOf(
                CustomField(key = "Database", value = "staging_db", isSensitive = false),
                CustomField(key = "Port", value = "5432", isSensitive = false),
            ),
            isFavorite = false,
            createdAt = now - 86_400_000L * 130,
            updatedAt = now - 86_400_000L * 130,
        ),
        Credential(
            id = "",
            title = "Redis Cloud",
            username = "default",
            password = "R3d1s\$ecure!C@che#",
            url = "redis://redis-12345.c1.us-east-1-3.ec2.cloud.redislabs.com:12345",
            notes = "Cache layer for production. 30 MB free tier.",
            otpParams = null,
            tags = listOf("Database"),
            customFields = listOf(
                CustomField(key = "Host", value = "redis-12345.c1.us-east-1-3.ec2.cloud.redislabs.com", isSensitive = false),
                CustomField(key = "Port", value = "12345", isSensitive = false),
            ),
            isFavorite = false,
            createdAt = now - 86_400_000L * 140,
            updatedAt = now - 86_400_000L * 140,
        ),
        Credential(
            id = "",
            title = "HBO Max",
            username = "john.doe@gmail.com",
            password = "HB0M@x\$ecure!Str3am",
            url = "https://max.com",
            notes = "Ad-free plan. Shared with partner.",
            otpParams = null,
            tags = listOf("Password"),
            customFields = emptyList(),
            isFavorite = false,
            createdAt = now - 86_400_000L * 145,
            updatedAt = now - 86_400_000L * 145,
        ),
        Credential(
            id = "",
            title = "npm Registry",
            username = "johndoe_npm",
            password = "npm\$ecure!Publ1sh#",
            url = "https://npmjs.com",
            notes = "Public packages only. Scoped: @johndoe.",
            otpParams = null,
            tags = listOf("Login"),
            customFields = listOf(
                CustomField(key = "Auth Token", value = "npm_xxxxxxxxxxxxxxxxxxxxxxxxxxxx", isSensitive = true),
            ),
            isFavorite = false,
            createdAt = now - 86_400_000L * 150,
            updatedAt = now - 86_400_000L * 150,
        ),
    )
}
