package com.roufsyed.onekey.core.domain.repository

import com.roufsyed.onekey.core.domain.model.AppResult
import com.roufsyed.onekey.core.security.KdfParams
import com.roufsyed.onekey.core.security.KdfPreset
import kotlinx.coroutines.flow.Flow

interface AuthRepository {
    fun isSetupComplete(): Flow<Boolean>
    suspend fun setupMasterPassword(password: CharArray): AppResult<Unit>

    /**
     * Sets up a brand-new vault with the Secret Key feature enabled. Mirrors
     * [setupMasterPassword] but additionally:
     *  - Wraps [secretKey] under the device's Keystore-backed SK wrapping key
     *    and persists the active wrapped blob.
     *  - Flips `SP_SECRET_KEY_ENABLED` to true so subsequent unlocks derive
     *    the verifier as `Argon2id(MP || SK, salt, params)`.
     *  - Installs [secretKey] into the in-memory holder so the unlocked
     *    session can render the Emergency Kit, write V5 backups, etc.
     *  - Sets the vault key on [com.roufsyed.onekey.core.security.VaultKeyHolder] just
     *    like [setupMasterPassword].
     *
     * Memory hygiene: the implementation defensively copies [secretKey]
     * inside the wrap step and zeros its own copies in finally; the
     * caller-owned [secretKey] is NOT zeroed by this method (consistent
     * with the existing [setupMasterPassword] convention of caller-owned
     * arrays). Caller MUST zero [secretKey] after this returns, typically
     * via `holder.withBytes { sk -> setupMasterPasswordWithSecretKey(pwd, sk) }`
     * which zeros its defensive copy on lambda exit.
     *
     * @param password The user-typed master password. Implementation zeros
     *                 this in a finally block.
     * @param secretKey The 16-byte plaintext Secret Key generated by the
     *                  caller. Must be exactly 16 bytes; implementation
     *                  rejects other lengths with [IllegalArgumentException].
     */
    suspend fun setupMasterPasswordWithSecretKey(
        password: CharArray,
        secretKey: ByteArray,
    ): AppResult<Unit>

    /**
     * Sets up a brand-new vault WITHOUT the Secret Key feature and records the
     * user's explicit opt-out. Equivalent to calling [setupMasterPassword] and
     * additionally setting the `sk_opted_out=true` persistent flag so the
     * Settings > Secret Key screen renders the "you opted out" surface
     * (state A with the opted-out tile) rather than the neutral "feature off"
     * surface.
     *
     * The opt-out flag is metadata only - it does NOT prevent a future
     * enable. The user can always turn Secret Key on later from Settings;
     * doing so generates a fresh SK and clears the opt-out flag. This
     * method exists so the onboarding skip path produces the same on-disk
     * state as a Settings-driven disable would, keeping the read side of
     * the Settings screen (`SecretKeyUiState.optedOut`) consistent.
     *
     * Memory hygiene mirrors [setupMasterPassword]: implementation zeros
     * the [password] array in a finally block.
     */
    suspend fun setupMasterPasswordOptingOutOfSecretKey(password: CharArray): AppResult<Unit>

    /**
     * Restores from an encrypted V5 backup where the SK feature was enabled
     * at export time. Mirrors [setupMasterPasswordWithSecretKey] for the
     * "this device just imported the SK from an Emergency Kit QR" flow:
     *  - Wraps [secretKey] under the local Keystore alias and persists the
     *    blob into [SP_SECRET_KEY_WRAPPED].
     *  - Flips `SP_SECRET_KEY_ENABLED=true` so subsequent unlocks derive
     *    the verifier with the SK mixed in.
     *  - Installs [secretKey] into [com.roufsyed.onekey.core.security.SecretKeyHolder]
     *    so the unlocked session can write fresh V5 exports.
     *  - Calls [setupMasterPassword] internally to set the vault key, salt,
     *    and verifier under the supplied [password].
     *
     * The caller (typically AuthViewModel.restoreFromEncryptedBackupWithSecretKey)
     * is responsible for parsing the backup file first (with the SK) and
     * importing the parsed credentials AFTER this method returns Success;
     * see [SetupFromBackupUseCase] for the SK-less analogue.
     *
     * Caller owns [password] and [secretKey] - the implementation zeros
     * neither (consistent with [setupMasterPasswordWithSecretKey]). The
     * password CharArray IS zeroed inside the wrapped [setupMasterPassword]
     * call as part of its existing contract.
     */
    suspend fun setupWithSecretKeyFromBackup(
        password: CharArray,
        secretKey: ByteArray,
    ): AppResult<Unit>

    suspend fun unlockWithPassword(password: CharArray): AppResult<Unit>
    suspend fun unlockWithPin(pin: CharArray): AppResult<Unit>
    suspend fun unlockWithBiometric(): AppResult<Unit>
    /**
     * Verifies a PIN matches the stored PIN_VALID hash WITHOUT setting the vault key on
     * the [com.roufsyed.onekey.core.security.VaultKeyHolder]. For in-vault flows that need to confirm
     * "the user knows the current PIN" (e.g. changing the PIN) without re-emitting Unlocked
     * state to anyone observing AuthRepository.isUnlocked / AuthViewModel.state.
     */
    suspend fun verifyPin(pin: CharArray): AppResult<Unit>

    /**
     * Verifies the master password matches the stored verifier WITHOUT setting
     * the vault key on [com.roufsyed.onekey.core.security.VaultKeyHolder] or triggering
     * any side effects (sync, silent KDF/Keystore migration, attempt-counter
     * resets in this repo's collaborators).
     *
     * Use for in-vault, already-unlocked reauth flows where the caller needs
     * to confirm "the user knows the current master password" before doing
     * something security-sensitive (changing KDF preset, exporting raw bytes,
     * etc.) but does not want the side effects of [unlockWithPassword].
     *
     * Defensively copies [password] internally so the caller retains ownership;
     * the implementation zeroes its copy in a finally block. Callers SHOULD
     * still zero their own [password] after this returns - the standard
     * `password.fill(' ')` pattern.
     *
     * Returns:
     *  - [AppResult.Success] when the verifier decrypts to the sentinel "VALID".
     *  - [AppResult.Error] on wrong password, missing/corrupted verifier, or
     *    unknown stored KDF version. The [AppResult.Error.message] is a
     *    user-facing string suitable for inline error UI.
     */
    suspend fun verifyMasterPassword(password: CharArray): AppResult<Unit>

    suspend fun setupPin(pin: CharArray): AppResult<Unit>
    suspend fun changePassword(oldPassword: CharArray, newPassword: CharArray): AppResult<Unit>
    suspend fun lock(): AppResult<Unit>
    fun isUnlocked(): Flow<Boolean>
    fun isPinSetup(): Flow<Boolean>
    suspend fun resetPin(): AppResult<Unit>
    suspend fun resetVault(): AppResult<Unit>
    suspend fun clearAll(): AppResult<Unit>

    /**
     * Observes the currently-active [KdfPreset] resolved from the stored
     * `SP_KDF_VERSION` integer. The flow emits the current value on collection
     * and re-emits whenever the verifier KDF version changes (e.g. after a
     * successful preset migration or a silent legacy -> v3 normalisation).
     *
     * Legacy codes (0 = PBKDF2, 1 = Argon2id Standard) are surfaced as
     * [KdfPreset.STANDARD] because that is the semantic config they represent.
     * A user who has never opened Settings > Encryption strength sees
     * "Standard" - which is correct, because Standard is what their vault was
     * created with (and what the silent verifier-migration path normalises to).
     */
    fun observeActiveKdfPreset(): Flow<KdfPreset>

    /**
     * Observes the currently-active custom (m, t) parameters, in MiB and
     * iterations respectively, emitted as a `Pair<m, t>`. Emits `null` when
     * the active preset is not [KdfPreset.CUSTOM] (i.e. one of the four fixed
     * presets is in effect or the legacy default is active).
     *
     * Used by the Settings UI to render the custom subtitle line
     * ("m=96 MiB, t=5") under the picker's selected-preset row. Mirrors the
     * pair shape the picker pushes back through `applyCustom(...)`.
     */
    fun observeActiveKdfCustomParams(): Flow<Pair<Int, Int>?>

    /**
     * Returns the currently-active Argon2id [KdfParams] for verifier and
     * V5-export derivation. Reads the same SP_KDF_VERSION + custom (m, t)
     * side-table that the unlock path consults, so the V5 envelope's
     * embedded KDF block records the exact preset the user is running.
     *
     * Legacy PBKDF2 vaults (kdf_version=0) are surfaced as the Argon2id
     * Standard preset because that is the params shape any V5 manual export
     * MUST use - V5 mandates Argon2id. PBKDF2 callers are blocked elsewhere
     * (verifier-migration path) before they can reach an SK-protected
     * export, so this mapping is defence-in-depth rather than a route a
     * user can hit.
     *
     * Suspending because it awaits the one-time DataStore -> SharedPreferences
     * migration on first call, mirroring the rest of this repository's
     * read-after-init contract.
     */
    suspend fun activeKdfParams(): KdfParams

    /**
     * Returns `true` when the Secret Key feature is currently enabled on
     * this install (SP_SECRET_KEY_ENABLED=true and a wrapped blob is
     * present). Suspending so the call awaits the same one-time migration
     * gate as the rest of this repo's read APIs.
     *
     * Used by the manual encrypted-export path to decide whether to write
     * a V5 envelope with FLAGS bit 0 set. The actual SK bytes come from
     * [com.roufsyed.onekey.core.security.SecretKeyHolder] - this method only
     * reports the on-disk feature flag.
     */
    suspend fun isSecretKeyEnabled(): Boolean

    /**
     * Observes the Secret Key feature-enabled flag (`SP_SECRET_KEY_ENABLED`).
     * Emits the current value on collection and re-emits whenever an Enable
     * / Disable / Rotate transition flips the on-disk flag, so the Settings
     * surface stays in sync with the live state.
     *
     * Cold-start emission honours the one-time DataStore -> SharedPreferences
     * migration gate; the flow only emits after `migrationComplete` so
     * downstream consumers never see a transiently-empty default.
     */
    fun observeIsSecretKeyEnabled(): Flow<Boolean>

    /**
     * Observes the Secret Key opted-out flag (`SP_SK_OPTED_OUT`). True iff
     * the user has explicitly opted out of Secret Key (either during
     * onboarding via [setupMasterPasswordOptingOutOfSecretKey] or by
     * disabling SK from Settings). Cleared on every successful Enable so
     * the flag means "currently off AND was an explicit choice".
     *
     * The Settings > Security > Secret Key row renders a different subtitle
     * depending on the combination of this flag and
     * [observeIsSecretKeyEnabled]; the search index points users at the
     * same row regardless.
     */
    fun observeSecretKeyOptedOut(): Flow<Boolean>
}
